apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app

spec:
  selector:
    matchLabels:
      app: weather-app
  replicas: 5

  template:
    metadata:
      labels:
        app: weather-app
    spec:
      containers:
      - name: weatherdetails
        image: weatherdetails
        imagePullPolicy: Never