apiVersion: v1
kind: Service
metadata:
  app: weather-app
  labels:
    app: weather-app
spec:
  ports:
  - nodePort: 30500
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: weather-app
  type: NodePort